name: Build and Deploy Windows Executable

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows Executable
        run: |
          python -m PyInstaller --onefile --add-data "assets;assets" --name r6sfarm main.py
          echo D | xcopy assets dist\assets /e

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: R6S-Auto-Renown-Farm
          path: dist
